"""Repo-synthesized interoperability corpus fixtures (#892).

Every fixture byte string here is generated deterministically in-repo —
no third-party file is vendored, so the corpus is redistribution-safe by
construction. ``build_default_corpus_manifest`` seals the corpus into a
versioned :class:`InteropCorpusManifest` whose fixture pins
(``content_sha256`` + ``size_bytes``) make any drift a detectable
regression rather than silent acceptance.

``materialize_corpus`` writes the byte corpus under a directory the
harness reads; keeping bytes and manifest in sync is mechanical: the
manifest is built FROM the generated bytes.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from .cad_interop_corpus import (
    InteropCorpusManifest,
    InteropFixtureEntry,
    InteropFixtureProvenance,
    InteropSemanticAssertion,
    build_interop_fixture_entry,
)

INTEROP_CORPUS_ID = 'htdt-interop-corpus'
INTEROP_CORPUS_VERSION = '1'

_TS = '2026-10-08T00:00:00+00:00'


# ---------------------------------------------------------------------------
# Fixture payload generators — deterministic bytes, no clocks, no randomness
# ---------------------------------------------------------------------------


def _rew_text() -> bytes:
    # REW-style UTF-8 text measurement export: header lines + freq/dB rows.
    lines = [
        '* HTDT interop corpus synthesized REW measurement',
        '* Source: synthesized; measurement point MLP',
        'Freq(Hz) Level(dB)',
        '20.0 68.5',
        '40.0 71.0',
        '80.0 66.25',
        '160.0 73.0',
        '320.0 70.5',
    ]
    return ('\n'.join(lines) + '\n').encode('utf-8')


def _equalizer_apo() -> bytes:
    # Bounded Equalizer APO subset: device scope (recorded, opaque),
    # global preamp, one channel-scoped stage + a Delay, and one command
    # the importer deliberately retains as opaque (unsupported_command).
    lines = [
        'Device: HTDT Corpus Playback',
        'Preamp: -3.0 dB',
        'Channel: L',
        'Filter 1: ON PK Fc 80 Hz Gain -4.5 dB Q 2.0',
        'Filter 2: ON LS Fc 105 Hz Gain 3.0 dB',
        'Delay: 0.5 ms',
        'Channel: R',
        'Filter 3: ON NO Fc 4000 Hz Q 4.0',
        'Channel: ALL',
        'Eval: "1+1"',
    ]
    return ('\r\n'.join(lines) + '\r\n').encode('utf-8')


def _camilladsp() -> bytes:
    # CamillaDSP YAML subset: playback channel count, two Biquad filters
    # (one Peaking, one Lowshelf), a Gain step, and a mixer section that
    # the importer must retain as opaque rather than interpret.
    text = (
        'devices:\n'
        '  playback:\n'
        '    type: Wasapi\n'
        '    channels: 2\n'
        '    device: "HTDT Corpus Loopback"\n'
        '  capture:\n'
        '    type: Wasapi\n'
        '    channels: 2\n'
        'filters:\n'
        '  room_peak_l:\n'
        '    type: Biquad\n'
        '    parameters:\n'
        '      type: Peaking\n'
        '      freq: 62.5\n'
        '      gain: -6.0\n'
        '      q: 3.5\n'
        '  shelf_all:\n'
        '    type: Biquad\n'
        '    parameters:\n'
        '      type: Lowshelf\n'
        '      freq: 110.0\n'
        '      gain: 2.5\n'
        '      q: 0.9\n'
        '  trim:\n'
        '    type: Gain\n'
        '    parameters:\n'
        '      gain: -1.5\n'
        'mixers:\n'
        '  downmix:\n'
        '    channels:\n'
        '      in: 2\n'
        '      out: 1\n'
        '    mapping:\n'
        '      - dest: 0\n'
        '        sources:\n'
        '          - channel: 0\n'
        '            gain: -6.0\n'
        'pipeline:\n'
        '  - type: Filter\n'
        '    channels: [0]\n'
        '    names: [room_peak_l]\n'
        '  - type: Filter\n'
        '    names: [shelf_all, trim]\n'
    )
    return text.encode('utf-8')


def _clf_binary_cf1() -> bytes:
    # .CF1 binary distribution signature (PRONOM fmt/1944): lead byte
    # 0x40 then BD 0A 00 01, 'v1.0' marker at offset 20 — signature-only;
    # the payload stays opaque and unsupported BY DESIGN (#905).
    payload = bytearray(64)
    payload[0] = 0x40
    payload[1:5] = b'\xbd\x0a\x00\x01'
    payload[20:24] = b'v1.0'
    payload[24:] = b'\x00' * (len(payload) - 24)
    return bytes(payload)


def _clf_binary_cf2_v2() -> bytes:
    # .CF2 v2-generation binary signature (#952): lead byte 0x41 then
    # BD 0A 00 02, 'v2.0' marker at offset 20 — the signature the CLF
    # viewer kit's own clf2_v2_* samples carry. Signature-only; payload
    # stays opaque and unsupported BY DESIGN.
    payload = bytearray(64)
    payload[0] = 0x41
    payload[1:5] = b'\xbd\x0a\x00\x02'
    payload[20:24] = b'v2.0'
    payload[24:] = b'\x00' * (len(payload) - 24)
    return bytes(payload)


def _ifc_step() -> bytes:
    # Minimal metric IFC4X3_ADD2 model: project + site/building/storey
    # chain + one IfcSpace with extruded-area-solid geometry (metres).
    return (
        'ISO-10303-21;\n'
        'HEADER;\n'
        "FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');\n"
        "FILE_NAME('corpus-room.ifc','2026-10-08T00:00:00',"
        "('HTDT interop corpus'),('Cognition'),'htdt','v1','');\n"
        "FILE_SCHEMA(('IFC4X3_ADD2'));\n"
        'ENDSEC;\n'
        'DATA;\n'
        "#1=IFCPROJECT('gid-proj',$,'Corpus',$,$,$,$,(#20),#40);\n"
        '#10=IFCAXIS2PLACEMENT3D(#11,$,$);\n'
        '#11=IFCCARTESIANPOINT((0.,0.,0.));\n'
        "#20=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#10,$);\n"
        '#30=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);\n'
        '#40=IFCUNITASSIGNMENT((#30));\n'
        '#45=IFCAXIS2PLACEMENT3D(#46,$,$);\n'
        '#46=IFCCARTESIANPOINT((0.,0.,0.));\n'
        '#47=IFCLOCALPLACEMENT($,#45);\n'
        "#50=IFCSITE('gid-site',$,'Site',$,$,#47,$,$,.ELEMENT.,$,$,$,$,$);\n"
        "#51=IFCBUILDING('gid-bldg',$,'B',$,$,#47,$,$,.ELEMENT.,$,$,$);\n"
        "#52=IFCBUILDINGSTOREY('gid-storey',$,'L1',$,$,#53,$,$,.ELEMENT.,$,$,3.0);\n"
        '#53=IFCLOCALPLACEMENT(#47,#54);\n'
        '#54=IFCAXIS2PLACEMENT3D(#55,$,$);\n'
        '#55=IFCCARTESIANPOINT((0.,0.,3.0));\n'
        "#60=IFCRELAGGREGATES('a1',$,$,$,#1,(#50));\n"
        "#61=IFCRELAGGREGATES('a2',$,$,$,#50,(#51));\n"
        "#62=IFCRELAGGREGATES('a3',$,$,$,#51,(#52));\n"
        '#70=IFCLOCALPLACEMENT(#53,#71);\n'
        '#71=IFCAXIS2PLACEMENT3D(#72,$,$);\n'
        '#72=IFCCARTESIANPOINT((1.,2.,0.));\n'
        "#80=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,'L',#81);\n"
        '#81=IFCPOLYLINE((#82,#83,#84,#85,#86,#87));\n'
        '#82=IFCCARTESIANPOINT((0.,0.));\n'
        '#83=IFCCARTESIANPOINT((5.,0.));\n'
        '#84=IFCCARTESIANPOINT((5.,7.));\n'
        '#85=IFCCARTESIANPOINT((3.,7.));\n'
        '#86=IFCCARTESIANPOINT((3.,4.));\n'
        '#87=IFCCARTESIANPOINT((0.,4.));\n'
        '#90=IFCEXTRUDEDAREASOLID(#80,$,#91,2.8);\n'
        '#91=IFCDIRECTION((0.,0.,1.));\n'
        "#92=IFCSHAPEREPRESENTATION(#20,'Body','SweptSolid',(#90));\n"
        '#93=IFCPRODUCTDEFINITIONSHAPE($,$,(#92));\n'
        "#100=IFCSPACE('gid-space',$,'Theater',$,$,#70,#93,$,.ELEMENT.,.INTERNAL.,$);\n"
        "#240=IFCRELCONTAINEDINSPATIALSTRUCTURE('c1',$,$,$,(#100),#52);\n"
        'ENDSEC;\n'
        'END-ISO-10303-21;\n'
    ).encode('utf-8')


def _project_bundle_spec() -> bytes:
    # Spec for the htdt_project_bundle lane: the harness materializes
    # this scene into a repository, exports the bundle, re-imports it,
    # and asserts table-level semantic equality (not zip bytes).
    return (
        '{\n'
        '  "document_id": "interop-corpus-doc",\n'
        '  "display_name": "Interop Corpus Room",\n'
        '  "schema_version": 2,\n'
        '  "room": {"width_m": 6.0, "depth_m": 4.0, "height_m": 2.4},\n'
        '  "entities": [\n'
        '    {"entity_id": "speaker-fl", "kind": "speaker", "name": "FL",\n'
        '     "position_m": [1.0, 1.0, 1.0], "size_m": [0.22, 0.28, 0.42],\n'
        '     "speaker_role": "FL"},\n'
        '    {"entity_id": "point-mlp", "kind": "measurement_point",\n'
        '     "name": "MLP", "position_m": [3.0, 3.0, 1.1]}\n'
        '  ]\n'
        '}\n'
    ).encode('utf-8')


GENERATORS = {
    'rew/mlp-measurement.txt': _rew_text,
    'equalizer_apo/corpus-config.txt': _equalizer_apo,
    'camilladsp/corpus-config.yaml': _camilladsp,
    'clf/vendor-binary.CF1': _clf_binary_cf1,
    'clf/vendor-binary-v2.CF2': _clf_binary_cf2_v2,
    'ifc/corpus-room.ifc': _ifc_step,
    'project_bundle/corpus-scene.json': _project_bundle_spec,
}


def _prov(
    tool: str, version: str, note: str = ''
) -> InteropFixtureProvenance:
    return InteropFixtureProvenance(
        source_kind='repo_synthesized',
        producer_tool=tool,
        producer_version=version,
        origin_note=note,
        licence_id='repo-synthesized',
        redistribution_state='repo_synthesized',
    )


def _entries() -> tuple[InteropFixtureEntry, ...]:
    return (
        build_interop_fixture_entry(
            format_family='rew_text',
            format_version='rew-text-1',
            relative_path='rew/mlp-measurement.txt',
            content_sha256=_sha(_rew_text()),
            size_bytes=len(_rew_text()),
            round_trip_mode='import_only',
            provenance=_prov(
                'rew-text-synthesizer', 'corpus-1',
                'REW-style UTF-8 text measurement export synthesized '
                'in-repo; no REW file bytes are vendored.',
            ),
            units_semantics='Hz / dB SPL line pairs',
            coordinate_semantics='n/a (measurement series, no geometry)',
            expected_supported_features=(
                'frequency_rows',
                'header_lines',
            ),
            expected_unsupported_features=(
                'phase_column',
                'export_to_rew_text',
            ),
            assertions=(
                InteropSemanticAssertion(
                    path='row_count', expected=5),
                InteropSemanticAssertion(
                    path='first_frequency_hz', expected=20.0),
                InteropSemanticAssertion(
                    path='last_frequency_hz', expected=320.0),
                InteropSemanticAssertion(
                    path='max_level_db', expected=73.0),
                InteropSemanticAssertion(
                    path='phase_present', expected=False),
                InteropSemanticAssertion(
                    path='phase_status', expected='absent'),
                InteropSemanticAssertion(
                    path='level_reference', expected='unknown'),
            ),
        ),
        build_interop_fixture_entry(
            format_family='equalizer_apo',
            format_version='apo-config-subset-1',
            relative_path='equalizer_apo/corpus-config.txt',
            content_sha256=_sha(_equalizer_apo()),
            size_bytes=len(_equalizer_apo()),
            round_trip_mode='round_trip',
            provenance=_prov(
                'apo-config-synthesizer', 'corpus-1',
                'Bounded Equalizer APO subset config synthesized in-repo.',
            ),
            units_semantics='Hz / dB / ms (delay normalizes to seconds)',
            coordinate_semantics='n/a',
            expected_supported_features=(
                'global_preamp',
                'channel_scoped_peq',
                'delay_ms',
            ),
            expected_unsupported_features=(
                'eval_command',
                'device_output_binding',
            ),
            # 'Eval:' is not modeled — retained opaque on import and
            # dropped by the bounded subset export; declared, not silent.
            expected_degradations=(
                'opaque:unsupported_command',
                'opaque:device_scope',
            ),
            expected_warnings=(
                'channel L has no HTDT mapping',
                'channel R has no HTDT mapping',
                'channel label ALL is unmapped: apply-scope comparison is blocked',
            ),
            assertions=(
                InteropSemanticAssertion(
                    path='import.format_id',
                    expected='equalizer-apo-config-txt'),
                InteropSemanticAssertion(
                    path='import.global_preamp_db', expected=-3.0),
                # L, R and the 'ALL' pseudo-channel APO creates for
                # unscoped command buckets.
                InteropSemanticAssertion(
                    path='import.channel_count', expected=3),
                InteropSemanticAssertion(
                    path='channel.L.band_count', expected=2),
                InteropSemanticAssertion(
                    path='channel.L.band.0.filter_type',
                    expected='peaking'),
                InteropSemanticAssertion(
                    path='channel.L.band.0.frequency_hz',
                    expected=80.0),
                InteropSemanticAssertion(
                    path='channel.L.band.0.gain_db', expected=-4.5),
                InteropSemanticAssertion(
                    path='channel.L.band.0.q', expected=2.0),
                InteropSemanticAssertion(
                    path='channel.L.delay_s',
                    comparator='approx', expected=0.0005,
                    tolerance=1e-9),
                InteropSemanticAssertion(
                    path='channel.R.band.0.filter_type',
                    expected='notch'),
                InteropSemanticAssertion(
                    path='roundtrip.semantic_equal', expected=True),
            ),
        ),
        build_interop_fixture_entry(
            format_family='camilladsp',
            format_version='camilladsp-yaml-subset-1',
            relative_path='camilladsp/corpus-config.yaml',
            content_sha256=_sha(_camilladsp()),
            size_bytes=len(_camilladsp()),
            round_trip_mode='import_only',
            provenance=_prov(
                'camilladsp-config-synthesizer', 'corpus-1',
                'CamillaDSP YAML subset synthesized in-repo; mixers '
                'are declared opaque, not interpreted.',
            ),
            units_semantics='Hz / dB (Gain step accumulates preamp)',
            coordinate_semantics='n/a',
            expected_supported_features=(
                'biquad_peq',
                'gain_step',
                'playback_channel_buckets',
            ),
            expected_unsupported_features=(
                'mixer_routing',
            ),
            expected_degradations=(
                'opaque:unsupported_command',
            ),
            expected_warnings=(
                'channel playback:0 has no HTDT mapping',
                'channel playback:1 has no HTDT mapping',
            ),
            assertions=(
                InteropSemanticAssertion(
                    path='import.format_id', expected='camilladsp-config'),
                InteropSemanticAssertion(
                    path='import.channel_count', expected=2),
                InteropSemanticAssertion(
                    path='channel.playback:0.band_count', expected=2),
                InteropSemanticAssertion(
                    path='channel.playback:0.band.0.filter_type',
                    expected='peaking'),
                InteropSemanticAssertion(
                    path='channel.playback:0.band.0.frequency_hz',
                    expected=62.5),
                InteropSemanticAssertion(
                    path='channel.playback:0.band.0.gain_db',
                    expected=-6.0),
                InteropSemanticAssertion(
                    path='channel.playback:0.band.0.q', expected=3.5),
                InteropSemanticAssertion(
                    path='channel.playback:0.preamp_db',
                    expected=-1.5),
                InteropSemanticAssertion(
                    path='channel.playback:1.band_count', expected=1),
            ),
        ),
        build_interop_fixture_entry(
            format_family='clf',
            format_version='cf1',
            relative_path='clf/vendor-binary.CF1',
            content_sha256=_sha(_clf_binary_cf1()),
            size_bytes=len(_clf_binary_cf1()),
            round_trip_mode='unsupported_assert',
            provenance=_prov(
                'clf-signature-synthesizer', 'corpus-1',
                'Signature-only .CF1 binary stub synthesized in-repo; '
                'no licensed speaker data is vendored — the family is '
                'unsupported by design (#905) and the corpus asserts '
                'exactly that.',
            ),
            units_semantics='n/a (opaque binary)',
            coordinate_semantics='n/a',
            expected_supported_features=(
                'binary_family_identification',
            ),
            expected_unsupported_features=(
                'polar_balloon_parse',
            ),
            assertions=(
                InteropSemanticAssertion(
                    path='verdict', expected='unsupported'),
                InteropSemanticAssertion(
                    path='family', expected='binary_cf1'),
            ),
        ),
        build_interop_fixture_entry(
            format_family='clf',
            format_version='cf2_v2',
            relative_path='clf/vendor-binary-v2.CF2',
            content_sha256=_sha(_clf_binary_cf2_v2()),
            size_bytes=len(_clf_binary_cf2_v2()),
            round_trip_mode='unsupported_assert',
            provenance=_prov(
                'clf-signature-synthesizer', 'corpus-1',
                'Signature-only .CF2 v2-generation binary stub '
                'synthesized in-repo; mirrors the viewer kit\'s real '
                'clf2_v2_* signature (#952) — the family stays '
                'unsupported by design and the corpus asserts exactly '
                'that.',
            ),
            units_semantics='n/a (opaque binary)',
            coordinate_semantics='n/a',
            expected_supported_features=(
                'binary_family_identification',
            ),
            expected_unsupported_features=(
                'polar_balloon_parse',
            ),
            assertions=(
                InteropSemanticAssertion(
                    path='verdict', expected='unsupported'),
                InteropSemanticAssertion(
                    path='family', expected='binary_cf2'),
                InteropSemanticAssertion(
                    path='binary_variant', expected='cf2_v2'),
            ),
        ),
        build_interop_fixture_entry(
            format_family='ifc_step',
            format_version='IFC4X3_ADD2',
            relative_path='ifc/corpus-room.ifc',
            content_sha256=_sha(_ifc_step()),
            size_bytes=len(_ifc_step()),
            round_trip_mode='round_trip',
            provenance=_prov(
                'ifc-step-synthesizer', 'corpus-1',
                'Metric IFC4X3 model synthesized in-repo (project/site/'
                'storey + one extruded space).',
            ),
            units_semantics='IFCSIUNIT METRE (length_scale_to_meter 1.0)',
            coordinate_semantics=(
                'IfcLocalPlacement chain; world_transform_m in metres'
            ),
            expected_supported_features=(
                'spatial_hierarchy',
                'extruded_area_solid_geometry',
                'metric_units',
            ),
            expected_unsupported_features=(),
            assertions=(
                InteropSemanticAssertion(
                    path='import.mapped_entity_count', expected=1),
                InteropSemanticAssertion(
                    path='import.coordinate.length_scale_to_meter',
                    expected=1.0),
                InteropSemanticAssertion(
                    path='room_candidate.count', expected=1),
                InteropSemanticAssertion(
                    path='room.Theater.profile_vertex_count',
                    expected=6),
                InteropSemanticAssertion(
                    path='room.Theater.extrusion_depth_m',
                    comparator='approx', expected=2.8,
                    tolerance=1e-9),
                InteropSemanticAssertion(
                    path='room.Theater.world_position_x_m',
                    comparator='approx', expected=1.0,
                    tolerance=1e-9),
                InteropSemanticAssertion(
                    path='roundtrip.room_geometry_equal', expected=True),
            ),
        ),
        build_interop_fixture_entry(
            format_family='htdt_project_bundle',
            format_version='htdt.project-bundle-1.0.0',
            relative_path='project_bundle/corpus-scene.json',
            content_sha256=_sha(_project_bundle_spec()),
            size_bytes=len(_project_bundle_spec()),
            round_trip_mode='round_trip',
            provenance=_prov(
                'bundle-spec-synthesizer', 'corpus-1',
                'Scene spec materialized then exported to .htdtproject '
                'in-repo; archival round-trip compares table rows, not '
                'zip bytes.',
            ),
            units_semantics='metres (SceneDocument SI)',
            coordinate_semantics='local scene coordinates',
            expected_supported_features=(
                'scene_revision_rows',
                'document_closure',
            ),
            expected_unsupported_features=(),
            assertions=(
                InteropSemanticAssertion(
                    path='bundle.contains_document', expected=True),
                InteropSemanticAssertion(
                    path='bundle.table_count', expected=2),
                InteropSemanticAssertion(
                    path='bundle.core_table_names',
                    comparator='set_equals',
                    expected=['scene_document_heads', 'scene_revisions']),
                InteropSemanticAssertion(
                    path='roundtrip.core_rows_equal', expected=True),
                InteropSemanticAssertion(
                    path='roundtrip.row_sets_equal', expected=True),
                # Re-import mints the project-library registration row;
                # that addition is declared provenance, not drift.
                InteropSemanticAssertion(
                    path='roundtrip.new_tables',
                    comparator='set_equals',
                    expected=['htdt_project_documents']),
                InteropSemanticAssertion(
                    path='roundtrip.document_id', expected='interop-corpus-doc'),
            ),
        ),
    )


def _sha(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def build_default_corpus_manifest(
    *, issued_on: str = _TS
) -> InteropCorpusManifest:
    """Seal the default in-repo corpus manifest."""
    return InteropCorpusManifest.create(
        corpus_id=INTEROP_CORPUS_ID,
        corpus_version=INTEROP_CORPUS_VERSION,
        issued_on=issued_on,
        fixtures=_entries(),
    )


def default_fixture_bytes() -> dict[str, bytes]:
    """Fresh deterministic bytes for every default fixture path."""
    return {path: gen() for path, gen in GENERATORS.items()}


def materialize_corpus(
    manifest: InteropCorpusManifest,
    target_dir: Path,
    *,
    payload_overrides: dict[str, bytes] | None = None,
) -> None:
    """Write corpus files under *target_dir* matching *manifest*.

    ``payload_overrides`` lets tests inject drifted bytes under a
    fixture's declared path; the harness then reports the pin mismatch
    as ``unexpected_failure`` (fixture drift is evidence, not a pass).
    """
    overrides = payload_overrides or {}
    bytes_map = default_fixture_bytes()
    for entry in manifest.fixtures:
        payload = overrides.get(entry.relative_path)
        if payload is None:
            payload = bytes_map.get(entry.relative_path)
        if payload is None:
            raise ValueError(
                f'no generated bytes for fixture {entry.relative_path}'
            )
        path = target_dir / entry.relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)


__all__ = [
    'GENERATORS',
    'INTEROP_CORPUS_ID',
    'INTEROP_CORPUS_VERSION',
    'build_default_corpus_manifest',
    'default_fixture_bytes',
    'materialize_corpus',
]
