"""Cross-repo compatibility gate against pinned HTDT-Capture fixtures (#334).

The vendored phase6-integration fixture was generated by HTDT-Capture at
pinned commit ``daa00b122f399050c29ba3af988b1d6438686746``; this module
verifies the machine-readable registry (``docs/CAPTURE_COMPATIBILITY.json``)
stays in lockstep with reality: the fixture manifest digests to the
registered bundle digest, the built plan hashes to the registered
canonical plan digest, and the lineage digest is frozen.

Updating an identity intentionally requires editing BOTH the registry
and this gate's single source of truth — the registry — in the same PR,
which makes pin bumps explicit and reviewable.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from htdt.capture_bundle import FrozenBundle
from htdt.capture_reference import build_ingestion_plan

BACKEND = Path(__file__).resolve().parents[1]
REPO = BACKEND.parent
REGISTRY_PATH = REPO / 'docs' / 'CAPTURE_COMPATIBILITY.json'
FIXTURE_ROOT = BACKEND / 'tests' / 'fixtures' / 'capture'
REFERENCE_PLAN = FIXTURE_ROOT / 'reference-ingestion-plan.json'


def _registry() -> dict:
    return json.loads(REGISTRY_PATH.read_text(encoding='utf-8'))


def _fixture_plan() -> tuple[dict, dict]:
    registry = _registry()
    frozen = FrozenBundle(FIXTURE_ROOT / registry['fixture']['kind'])
    plan = build_ingestion_plan(frozen)
    return registry, plan


def test_pinned_fixture_bundle_digest_matches_registry() -> None:
    registry = _registry()
    frozen = FrozenBundle(FIXTURE_ROOT / registry['fixture']['kind'])
    assert frozen.report['bundle_digest'] == registry['fixture']['bundle_digest']
    assert (
        frozen.report['bundle_digest']
        == hashlib.sha256(frozen.manifest_bytes).hexdigest()
    )


def test_pinned_ingestion_plan_identity_is_frozen() -> None:
    registry, plan = _fixture_plan()
    expected = registry['expectations']
    canonical = json.dumps(
        plan, sort_keys=True, separators=(',', ':')
    ).encode('utf-8')
    assert (
        hashlib.sha256(canonical).hexdigest()
        == expected['ingestion_plan_canonical_sha256']
    )
    assert plan['lineage_digest'] == expected['lineage_digest']
    assert plan['ingestor'] == {
        'name': registry['upstream']['ingestor']['name'],
        'version': registry['upstream']['ingestor']['version'],
        'configuration_digest': (
            registry['upstream']['ingestor']['configuration_digest']
        ),
    }
    counts = expected['counts']
    assert len(plan['source_evidence']) == counts['source_evidence']
    assert len(plan['roomplan_records']) == counts['roomplan_records']
    assert (
        len(plan['raw_visual_mesh_handoffs'])
        == counts['raw_visual_mesh_handoffs']
    )
    assert len(plan['authority_records']) == counts['authority_records']


def test_reference_plan_file_is_the_pinned_canonical_plan() -> None:
    """The checked-in reference plan must equal the pinned digests."""
    registry = _registry()
    raw = REFERENCE_PLAN.read_bytes()
    canonical = json.dumps(
        json.loads(raw), sort_keys=True, separators=(',', ':')
    ).encode('utf-8')
    assert (
        hashlib.sha256(canonical).hexdigest()
        == registry['expectations']['ingestion_plan_canonical_sha256']
    )


def test_registry_declares_the_pinned_upstream_commit() -> None:
    registry = _registry()
    upstream = registry['upstream']
    assert upstream['repository'] == 'ka0923s-a11y/HTDT-Capture'
    assert len(upstream['pinned_commit']) == 40
    int(upstream['pinned_commit'], 16)
    assert upstream['bundle_schema'] == 'htdt.capture.bundle'
    assert upstream['bundle_schema_version'] == '1.0.0'
