#!/usr/bin/env python3
"""Regenerate the pinned cross-repo equipment catalog snapshot fixture (#366).

The fixture pins what HTDT-Capture sees when it consumes an
htdt.equipment.catalog-snapshot v1 document. It is generated by the real
EquipmentCatalogSnapshot model so the on-disk bytes match production
serialization exactly; update it only through a deliberate protocol-change
commit, never as a side effect of refactors.

Usage:
    python scripts/generate_equipment_catalog_fixture.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from tempfile import NamedTemporaryFile

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / 'backend' / 'src'))

from htdt.cad_equipment import (  # noqa: E402
    DirectivityCapability,
    EquipmentDataProvenance,
    build_equipment_definition,
)
from htdt.cad_equipment_catalog import build_equipment_catalog_snapshot  # noqa: E402
from htdt.cad_scene import Offset3, Size3  # noqa: E402

FIXTURE_PATH = (
    REPO_ROOT
    / 'backend'
    / 'tests'
    / 'fixtures'
    / 'equipment_catalog_snapshot_v1.json'
)


def _provenance(evidence_kind: str, reference: str, sha: str):
    return EquipmentDataProvenance(
        evidence_kind=evidence_kind,
        source_name='HTDT cross-repo fixture',
        source_version='1',
        source_reference=reference,
        source_sha256=sha,
    )


def _directivity(provenance):
    return DirectivityCapability(
        tier='unknown',
        data_format='unknown',
        provenance=provenance,
        coherent_phase=False,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0] if __doc__ else None,
    )
    parser.parse_args()
    manufacturer = _provenance('manufacturer', 'datasheet:fixture', 'a' * 64)
    user = _provenance('user_defined', 'manual:fixture', 'b' * 64)
    definitions = (
        build_equipment_definition(
            definition_id='fixture-av-receiver',
            version='1',
            identity_kind='user_defined',
            user_label='AVR Reference',
            provenance=(user,),
            cabinet_envelope_m=Size3(x_m=0.435, y_m=0.168, z_m=0.379),
            acoustic_reference_point_m=Offset3(),
            directivity=_directivity(user),
        ),
        build_equipment_definition(
            definition_id='fixture-bookshelf',
            version='1',
            identity_kind='manufacturer',
            manufacturer='Fixture Acoustics',
            model='FB-1 Bookshelf',
            provenance=(manufacturer,),
            cabinet_envelope_m=Size3(x_m=0.190, y_m=0.340, z_m=0.280),
            acoustic_reference_point_m=Offset3(
                x_m=0.0,
                y_m=0.05,
                z_m=0.06,
            ),
            directivity=_directivity(manufacturer),
        ),
        build_equipment_definition(
            definition_id='fixture-sub',
            version='1',
            identity_kind='manufacturer',
            manufacturer='Fixture Acoustics',
            model='FS-10 Subwoofer',
            provenance=(manufacturer,),
            cabinet_envelope_m=Size3(x_m=0.320, y_m=0.400, z_m=0.350),
            acoustic_reference_point_m=Offset3(
                x_m=0.0,
                y_m=0.10,
                z_m=0.05,
            ),
            directivity=_directivity(manufacturer),
        ),
    )
    snapshot = build_equipment_catalog_snapshot(definitions)
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Write through a temp file so a failed regeneration never leaves a
    # truncated fixture behind.
    with NamedTemporaryFile(
        mode='wb',
        dir=FIXTURE_PATH.parent,
        delete=False,
    ) as handle:
        handle.write(snapshot.canonical_bytes())
        temp_path = Path(handle.name)
    temp_path.replace(FIXTURE_PATH)
    print(f'wrote {FIXTURE_PATH} ({len(snapshot.definitions)} entries)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
